language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run lint
  - npm run test:prod
  - npm run build
after_success:
  - npm run report-coverage
  # - ./tools/deploy.sh # disabled for now
